apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 306015045840.dkr.ecr.us-east-1.amazonaws.com/calmhaven-frontend:latest
          ports:
            - containerPort: 80